version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: new_docker_user
      POSTGRES_DB: new_docker_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - postgresql
  ws:
    image: fastapi_test:v1.3.5
    restart: always
    environment:
      DEST_EMAIL: ${DEST_EMAIL}
      SRC_EMAIL: ${SRC_EMAIL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - postgresql
networks:
  postgresql:
    driver: bridge
