name: Deploy to EC2 

on:
  push:
    branches: [ "dev-1.4.9" ]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.DEV_EC2_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.DEV_EC2_IP  }}
            USER_NAME : ${{ secrets.DEV_EC2_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ec2-user &&
            docker run -it --rm -d -p 8080:80 --name web nginx
          '

