name: CI/CD SSLV WebScraper

on:
  push:
    branches: [ "dev-1.4.9" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup creating database.ini env file 
      run: |
        ls -la
        echo "[postgresql]" > src/ws/database.ini
        echo "host=db" >> src/ws/database.ini
        echo "${{ secrets.PG_DB_NAME }}" >> src/ws/database.ini
        echo "${{ secrets.PG_DB_USER }}" >> src/ws/database.ini
        echo "${{ secrets.PG_DB_PASS }}" >> src/ws/database.ini
        ls -la
        cat src/ws/database.ini
    
    - name: Before build step 2 create .env.prod file
      run: |
        ls -la
        echo "# ws_worker container env variables" > .env.prod
        echo "${{ secrets.DEST_EMAIL }}" >> .env.prod 
        echo "${{ secrets.SRC_EMAIL }}" >> .env.prod 
        echo "${{ secrets.SENDGRID_API_KEY }}" >> .env.prod
        echo "# postgres db container env variable" >> .env.prod
        echo "${{ secrets.POSTGRES_PASSWORD }}" >> .env.prod 
        ls -la
    
    - name: Start DB container ONLY
      run: docker-compose --env-file .env.prod up -d
    
    - name: List DB table sizes to confirm if DB import was correct
      run: |
        sleep 10
        docker-compose ps
        docker exec sslv_web_scraper_db_1  psql -U new_docker_user -d new_docker_db -c '\dt+'
        
    - name: Run docker compose ps
      run: docker-compose ps
      
    - name: Run compose down
      run: docker-compose down
